### Import library

In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\sujat\Downloads\Online Payment fraud detection.csv")
data

step      type     amount     nameOrig  oldbalanceOrg  \
0           1   PAYMENT    9839.64  C1231006815      170136.00   
1           1   PAYMENT    1864.28  C1666544295       21249.00   
2           1  TRANSFER     181.00  C1305486145         181.00   
3           1  CASH_OUT     181.00   C840083671         181.00   
4           1   PAYMENT   11668.14  C2048537720       41554.00   
...       ...       ...        ...          ...            ...   
1048570    95  CASH_OUT  132557.35  C1179511630      479803.00   
1048571    95   PAYMENT    9917.36  C1956161225       90545.00   
1048572    95   PAYMENT   14140.05  C2037964975       20545.00   
1048573    95   PAYMENT   10020.05  C1633237354       90605.00   
1048574    95   PAYMENT   11450.03  C1264356443       80584.95   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
0             160296.36  M1979787155            0.00            0.00        0   
1              19384.72  M2044282225            0.00            0.00        0   
2                  0.00   C553264065            0.00            0.00        1   
3                  0.00    C38997010        21182.00            0.00        1   
4              29885.86  M1230701703            0.00            0.00        0   
...                 ...          ...             ...             ...      ...   
1048570       347245.65   C435674507       484329.37       616886.72        0   
1048571        80627.64   M668364942            0.00            0.00        0   
1048572         6404.95  M1355182933            0.00            0.00        0   
1048573        80584.95  M1964992463            0.00            0.00        0   
1048574        69134.92   M677577406            0.00            0.00        0   

         isFlaggedFraud  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
...                 ...  
1048570               0  
1048571               0  
1048572               0  
1048573               0  
1048574               0  

[1048575 rows x 11 columns]

### What is Data Mining ?
##### Data Mining is a process of extracting and discovering patterns in large datasets involving methods at the
#### intersection of machine learning,statistics and AI.
#### The main purpose of data mining is to extract valuable information from available data.

In [3]:
data1=data.iloc[:,[1,2,4,5,7,8,9]]
data1

type     amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0         PAYMENT    9839.64      170136.00       160296.36            0.00   
1         PAYMENT    1864.28       21249.00        19384.72            0.00   
2        TRANSFER     181.00         181.00            0.00            0.00   
3        CASH_OUT     181.00         181.00            0.00        21182.00   
4         PAYMENT   11668.14       41554.00        29885.86            0.00   
...           ...        ...            ...             ...             ...   
1048570  CASH_OUT  132557.35      479803.00       347245.65       484329.37   
1048571   PAYMENT    9917.36       90545.00        80627.64            0.00   
1048572   PAYMENT   14140.05       20545.00         6404.95            0.00   
1048573   PAYMENT   10020.05       90605.00        80584.95            0.00   
1048574   PAYMENT   11450.03       80584.95        69134.92            0.00   

         newbalanceDest  isFraud  
0                  0.00        0  
1                  0.00        0  
2                  0.00        1  
3                  0.00        1  
4                  0.00        0  
...                 ...      ...  
1048570       616886.72        0  
1048571            0.00        0  
1048572            0.00        0  
1048573            0.00        0  
1048574            0.00        0  

[1048575 rows x 7 columns]

### What is data preprocessing ?
##### Data preprocessing is a technique that is used in dataset to convert the raw data into a clean dataset.
##### and making it suitable for a machine learning model.
#### It is the first and crucial step while creating a machine learning model.

In [4]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
data1["type"]=l1.fit_transform(data1["type"])

C:\Users\sujat\AppData\Local\Temp\ipykernel_24092\1316437898.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1["type"]=l1.fit_transform(data1["type"])


In [5]:
data1

type     amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0           3    9839.64      170136.00       160296.36            0.00   
1           3    1864.28       21249.00        19384.72            0.00   
2           4     181.00         181.00            0.00            0.00   
3           1     181.00         181.00            0.00        21182.00   
4           3   11668.14       41554.00        29885.86            0.00   
...       ...        ...            ...             ...             ...   
1048570     1  132557.35      479803.00       347245.65       484329.37   
1048571     3    9917.36       90545.00        80627.64            0.00   
1048572     3   14140.05       20545.00         6404.95            0.00   
1048573     3   10020.05       90605.00        80584.95            0.00   
1048574     3   11450.03       80584.95        69134.92            0.00   

         newbalanceDest  isFraud  
0                  0.00        0  
1                  0.00        0  
2                  0.00        1  
3                  0.00        1  
4                  0.00        0  
...                 ...      ...  
1048570       616886.72        0  
1048571            0.00        0  
1048572            0.00        0  
1048573            0.00        0  
1048574            0.00        0  

[1048575 rows x 7 columns]

In [6]:
data1.isnull().sum()

type              0
amount            0
oldbalanceOrg     0
newbalanceOrig    0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
dtype: int64

In [7]:
data["isFraud"].value_counts()

0    1047433
1       1142
Name: isFraud, dtype: int64

In [8]:
data1.describe()

type        amount  oldbalanceOrg  newbalanceOrig  \
count  1.048575e+06  1.048575e+06   1.048575e+06    1.048575e+06   
mean   1.713400e+00  1.586670e+05   8.740095e+05    8.938089e+05   
std    1.345007e+00  2.649409e+05   2.971751e+06    3.008271e+06   
min    0.000000e+00  1.000000e-01   0.000000e+00    0.000000e+00   
25%    1.000000e+00  1.214907e+04   0.000000e+00    0.000000e+00   
50%    1.000000e+00  7.634333e+04   1.600200e+04    0.000000e+00   
75%    3.000000e+00  2.137619e+05   1.366420e+05    1.746000e+05   
max    4.000000e+00  1.000000e+07   3.890000e+07    3.890000e+07   

       oldbalanceDest  newbalanceDest       isFraud  
count    1.048575e+06    1.048575e+06  1.048575e+06  
mean     9.781600e+05    1.114198e+06  1.089097e-03  
std      2.296780e+06    2.416593e+06  3.298351e-02  
min      0.000000e+00    0.000000e+00  0.000000e+00  
25%      0.000000e+00    0.000000e+00  0.000000e+00  
50%      1.263772e+05    2.182604e+05  0.000000e+00  
75%      9.159235e+05    1.149808e+06  0.000000e+00  
max      4.210000e+07    4.220000e+07  1.000000e+00

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 11 columns):
 #   Column          Non-Null Count    Dtype  
---  ------          --------------    -----  
 0   step            1048575 non-null  int64  
 1   type            1048575 non-null  object 
 2   amount          1048575 non-null  float64
 3   nameOrig        1048575 non-null  object 
 4   oldbalanceOrg   1048575 non-null  float64
 5   newbalanceOrig  1048575 non-null  float64
 6   nameDest        1048575 non-null  object 
 7   oldbalanceDest  1048575 non-null  float64
 8   newbalanceDest  1048575 non-null  float64
 9   isFraud         1048575 non-null  int64  
 10  isFlaggedFraud  1048575 non-null  int64  
dtypes: float64(5), int64(3), object(3)
memory usage: 88.0+ MB


In [10]:
x=data1.iloc[:,:-1].values
y=data1.iloc[:,-1].values

### Standardized

In [11]:
from sklearn.preprocessing import StandardScaler
s1=StandardScaler()
s2=s1.fit_transform(x)
s2

array([[ 0.9565757 , -0.56173807, -0.23685497, -0.24383202, -0.42588334,
        -0.46106169],
       [ 0.9565757 , -0.59184049, -0.28695576, -0.29067345, -0.42588334,
        -0.46106169],
       [ 1.70006662, -0.59819391, -0.29404519, -0.29711726, -0.42588334,
        -0.46106169],
       ...,
       [ 0.9565757 , -0.54550648, -0.28719266, -0.29498814, -0.42588334,
        -0.46106169],
       [ 0.9565757 , -0.56105712, -0.26361732, -0.27032945, -0.42588334,
        -0.46106169],
       [ 0.9565757 , -0.55565977, -0.26698909, -0.27413563, -0.42588334,
        -0.46106169]])

In [12]:
data2=pd.DataFrame(s2)
data2

0         1         2         3         4         5
0        0.956576 -0.561738 -0.236855 -0.243832 -0.425883 -0.461062
1        0.956576 -0.591840 -0.286956 -0.290673 -0.425883 -0.461062
2        1.700067 -0.598194 -0.294045 -0.297117 -0.425883 -0.461062
3       -0.530406 -0.598194 -0.294045 -0.297117 -0.416661 -0.461062
4        0.956576 -0.554837 -0.280123 -0.287183 -0.425883 -0.461062
...           ...       ...       ...       ...       ...       ...
1048570 -0.530406 -0.098549 -0.132651 -0.181687 -0.215010 -0.205790
1048571  0.956576 -0.561445 -0.263638 -0.270315 -0.425883 -0.461062
1048572  0.956576 -0.545506 -0.287193 -0.294988 -0.425883 -0.461062
1048573  0.956576 -0.561057 -0.263617 -0.270329 -0.425883 -0.461062
1048574  0.956576 -0.555660 -0.266989 -0.274136 -0.425883 -0.461062

[1048575 rows x 6 columns]

In [13]:
x1=x
y1=y

In [14]:
from imblearn.over_sampling import SMOTE
sm=SMOTE()
x_data,y_data=sm.fit_resample(x1,y1)

In [15]:
from collections import Counter
print(Counter(y_data))

Counter({0: 1047433, 1: 1047433})


### Train_test_split

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.2,random_state=0)

### Using Decision Tree

### What is decision tree?
#### Decision Tree is classification supervised machine learning algorithm.
#### The gole is to create model that predicts the value of target variable by learning simple decision rule from
#### data feacture.
#### It learn from the conditional concepts like decision rule.
#### Every decision rules has some conditions.
#### The dipper the tree more complex the decision rule and fitter the model.

In [17]:
from sklearn import tree
d1=tree.DecisionTreeClassifier()
d1.fit(x_train,y_train)

DecisionTreeClassifier()

In [18]:
y_pred=d1.predict(x_test)
y_pred

array([1, 0, 0, ..., 1, 0, 0], dtype=int64)

In [19]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_pred,y_test)*100
print(acc)

99.87230711213584


### With Corss-validation technique

In [20]:
from sklearn.model_selection import KFold
k1=KFold(n_splits=5,random_state=11,shuffle=True)
k1.get_n_splits(x1)
print(k1)

KFold(n_splits=5, random_state=11, shuffle=True)


In [21]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
score=cross_val_score(d1,x_train,y_train,cv=k1)*100
pred=cross_val_predict(d1,x_test,y_test)
print(np.mean(score))
print(pred)

99.86204361211651
[1 0 0 ... 1 0 0]


#### End of coding